In [1]:
import tensorflow as tf 
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define the vocabulary Size 
voc_size = 10000 

In [5]:
# One Hot Representation for Every Word 
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr


[[8428, 5065, 2391, 7833],
 [8428, 5065, 2391, 997],
 [8428, 4456, 2391, 242],
 [5722, 5501, 5831, 2197, 4985],
 [5722, 5501, 5831, 2197, 4416],
 [8093, 8428, 9673, 2391, 6085],
 [581, 7425, 7847, 2197]]

In [6]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np 
import pandas as pd 

In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length) 
# Pad sequences helps us to match the length of all Sentences, this is will make them uniform
# Prepadding means the sentences are made up of same lenght, zeroes are added before
# Max lenght gives the uniform sentence lenght
print(embedded_docs)

[[   0    0    0    0 8428 5065 2391 7833]
 [   0    0    0    0 8428 5065 2391  997]
 [   0    0    0    0 8428 4456 2391  242]
 [   0    0    0 5722 5501 5831 2197 4985]
 [   0    0    0 5722 5501 5831 2197 4416]
 [   0    0    0 8093 8428 9673 2391 6085]
 [   0    0    0    0  581 7425 7847 2197]]


In [9]:
# Feature Representation 
dim = 10   # We want 10 features in word embeddings

In [10]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
# Model Embedding Layer added 
model.compile('adam','mse')

d:\Data Science Krish Naik\Sections\myenv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step


array([[[ 4.7319643e-03,  1.0654844e-02,  2.7785603e-02, -6.1878935e-03,
          5.8776736e-03, -3.7697803e-02, -1.3539016e-02,  2.3828592e-02,
          4.3503452e-02, -2.8902387e-02],
        [ 4.7319643e-03,  1.0654844e-02,  2.7785603e-02, -6.1878935e-03,
          5.8776736e-03, -3.7697803e-02, -1.3539016e-02,  2.3828592e-02,
          4.3503452e-02, -2.8902387e-02],
        [ 4.7319643e-03,  1.0654844e-02,  2.7785603e-02, -6.1878935e-03,
          5.8776736e-03, -3.7697803e-02, -1.3539016e-02,  2.3828592e-02,
          4.3503452e-02, -2.8902387e-02],
        [ 4.7319643e-03,  1.0654844e-02,  2.7785603e-02, -6.1878935e-03,
          5.8776736e-03, -3.7697803e-02, -1.3539016e-02,  2.3828592e-02,
          4.3503452e-02, -2.8902387e-02],
        [ 3.0260336e-02,  4.9368571e-02,  1.4942732e-02,  1.1012625e-02,
         -4.4532597e-02,  9.8488927e-03, -3.1681255e-02,  4.8745386e-03,
         -8.4254146e-03, -2.0854652e-02],
        [ 3.7532393e-02, -2.5182618e-02,  4.0904712e-02, -1.

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 8428, 5065, 2391, 7833])

In [15]:
model.predict[embedded_docs[0]]

TypeError: 'method' object is not subscriptable